awk '
/fun ExamCard\(/ {
    skip=1
    print "@Composable"
    print "fun ExamCard(exam: ExamEntity, onEdit: () -> Unit, onDelete: () -> Unit, onToggleStatus: () -> Unit) {"
    print "    Card("
    print "        modifier = Modifier.fillMaxWidth(),"
    print "        shape = RoundedCornerShape(16.dp),"
    print "        colors = CardDefaults.cardColors(containerColor = MaterialTheme.colorScheme.surface),"
    print "        elevation = CardDefaults.cardElevation(defaultElevation = 2.dp)"
    print "    ) {"
    print "        Column(modifier = Modifier.padding(16.dp)) {"
    print "            Row("
    print "                modifier = Modifier.fillMaxWidth(),"
    print "                horizontalArrangement = Arrangement.SpaceBetween,"
    print "                verticalAlignment = Alignment.CenterVertically"
    print "            ) {"
    print "                Row(verticalAlignment = Alignment.CenterVertically) {"
    print "                    if (exam.syncStatus == \"PENDING\") {"
    print "                        Icon(Icons.Default.Sync, contentDescription = \"Syncing\", modifier = Modifier.size(16.dp), tint = MaterialTheme.colorScheme.primary)"
    print "                        Spacer(modifier = Modifier.width(4.dp))"
    print "                    }"
    print "                    Text("
    print "                        text = exam.title,"
    print "                        style = MaterialTheme.typography.titleMedium,"
    print "                        fontWeight = FontWeight.Bold,"
    print "                        color = MaterialTheme.colorScheme.primary"
    print "                    )"
    print "                }"
    print "                Surface("
    print "                    shape = RoundedCornerShape(8.dp),"
    print "                    color = if (exam.status == \"Active\") MaterialTheme.colorScheme.primaryContainer else MaterialTheme.colorScheme.secondaryContainer"
    print "                ) {"
    print "                    Text("
    print "                        text = exam.status,"
    print "                        modifier = Modifier.padding(horizontal = 8.dp, vertical = 4.dp),"
    print "                        style = MaterialTheme.typography.labelSmall,"
    print "                        fontWeight = FontWeight.Bold,"
    print "                        color = if (exam.status == \"Active\") MaterialTheme.colorScheme.onPrimaryContainer else MaterialTheme.colorScheme.onSecondaryContainer"
    print "                    )"
    print "                }"
    print "            }"
    print "            Spacer(modifier = Modifier.height(4.dp))"
    print "            Text("
    print "                text = exam.subtitle,"
    print "                style = MaterialTheme.typography.bodyMedium,"
    print "                color = MaterialTheme.colorScheme.onSurfaceVariant"
    print "            )"
    print "            Spacer(modifier = Modifier.height(12.dp))"
    print "            Row("
    print "                modifier = Modifier.fillMaxWidth(),"
    print "                horizontalArrangement = Arrangement.End,"
    print "                verticalAlignment = Alignment.CenterVertically"
    print "            ) {"
    print "                TextButton(onClick = onEdit) {"
    print "                    Icon(Icons.Default.Edit, contentDescription = null, modifier = Modifier.size(16.dp))"
    print "                    Spacer(modifier = Modifier.width(4.dp))"
    print "                    Text(\"Edit\")"
    print "                }"
    print "                Spacer(modifier = Modifier.width(4.dp))"
    print "                TextButton(onClick = onToggleStatus) {"
    print "                    Icon(Icons.Default.Refresh, contentDescription = null, modifier = Modifier.size(16.dp))"
    print "                    Spacer(modifier = Modifier.width(4.dp))"
    print "                    Text(if (exam.status == \"Active\") \"Set Upcoming\" else \"Set Active\")"
    print "                }"
    print "                Spacer(modifier = Modifier.width(4.dp))"
    print "                TextButton("
    print "                    onClick = onDelete,"
    print "                    colors = ButtonDefaults.textButtonColors(contentColor = MaterialTheme.colorScheme.error)"
    print "                ) {"
    print "                    Icon(Icons.Default.Delete, contentDescription = null, modifier = Modifier.size(16.dp))"
    print "                    Spacer(modifier = Modifier.width(4.dp))"
    print "                    Text(\"Delete\")"
    print "                }"
    print "            }"
    print "        }"
    print "    }"
    print "}"
}
skip==1 && /^}$/ { skip=0; next }
skip==0 { print }
' app/src/main/java/com/example/ui/screens/ManageExamsScreen.kt > temp_manage_exams.kt
mv temp_manage_exams.kt app/src/main/java/com/example/ui/screens/ManageExamsScreen.kt
